### ISSUE TITLE
check if file exists before demultiplexing

### ISSUE THREAD

**Issue by ColinAnthony** [ColinAnthony/NGS_processing_pipeline#2]

**Comment by jambler24** [comment]
The aim here is to not only to check if the demultiplexed fastq files for each gene exist, but also to see if they are complete or not. So my current plan is to also have a file created in the directory, that is deleted once the demultiplexing is complete. That way, if the file is still there, we know that demultiplexing may have been interrupted.

**Comment by jambler24** [comment]
Also, is this not a repeat of issue 1?

**Comment by jambler24** [comment]
Done. But because of the danger of removing entire directories, if a run is interrupted and intermediary files remain, the pipeline will stop and ask the user to remove the files in the output directory manually before running the pipeline again.

**Comment by jambler24** [comment]
The pipeline creates a file called 'setup_log.csv' in the output directory to track which files have been processed.

**Comment by ColinAnthony** [comment]
edge cases..
what happens if the pipeline breaks unexpectedly?
I guess what I mean is, when does the file get created.
I assume it is after the completion of the demultiplex step.
If there is a crash during demultiplexing, you will have have some partially created files.
is this handled?
or does it just remove the output file if it detects that is has already been made?

If these are handled, we can close this issue

**Comment by jambler24** [comment]
We handled this by checking if the demultiplexing run completed, if not, all the incomplete files are removed and the process started again. This is because we have no way of knowing which reads were the last to be processed in a batch.
